version: '3.8'

services:

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always

  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: app_mysql
    ports:
      - "3345:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  golang-app:
    build: .
    container_name: golang_app
    depends_on:
      - database
    env_file:
      - ./.env   
    ports:
      - "8066:8080"  # Port internal di dalam container 8080 sesuai dengan APP_PORT
    volumes:
      - .:/go/src/app
    command: ["./main"]
    restart: always

volumes:
  db_data:
